install:
  - appveyor DownloadFile https://download.microsoft.com/download/6/E/B/6EBD972D-2E2F-41EB-9668-F73F5FDDC09C/dotnet-hosting-2.1.3-win.exe
  - dotnet-hosting-2.1.3-win.exe /install /norestart /quiet
