image: Visual Studio 2019

services:
  - iis

install:
  - choco install dotnet-aspnetcoremodule-v2

build_script:
  - dotnet --version
  - dotnet --info
  - cd Build
  - dotnet restore Build.csproj
  - dotnet msbuild Build.csproj
